### ISSUE TITLE
Depth factor

### ISSUE THREAD

**Issue by kuwan2e** [Sangluisme/PSgradientSDF#2]
Hi. Could you please tell me the depth factor for tum, multiview and synth?
I think maybe the value of tum data is 5000, but what about multiview and synth?
Thanks!

**Comment by Sangluisme** [comment]
tum is 1/5000 
see here: https://github.com/Sangluisme/PSgradientSDF/blob/ee5bb0289e33f7b82dec8504fb9650dc7ac2ff06/cpp/include/img_loader/TumrgbdLoader.h#L35

synth is 1/1000
see here:
https://github.com/Sangluisme/PSgradientSDF/blob/ee5bb0289e33f7b82dec8504fb9650dc7ac2ff06/cpp/include/img_loader/SynthLoader.h#L24

multiview is 1/1000
see here:
https://github.com/Sangluisme/PSgradientSDF/blob/ee5bb0289e33f7b82dec8504fb9650dc7ac2ff06/cpp/include/img_loader/MultiviewLoader.h#L29
