### ISSUE TITLE
Question about output mesh only contains one image 

### ISSUE THREAD

**Issue by kuwan2e** [Sangluisme/PSgradientSDF#3]
Hi , I have a sequence of RGBD images . But the result of reconstruction seems only contain the first image. Could you please give some suggestions?
![image](https://github.com/Sangluisme/PSgradientSDF/assets/42766628/7469c7dc-2c17-40a7-8674-6238f49fa813)
![image](https://github.com/Sangluisme/PSgradientSDF/assets/42766628/5e01ca11-b141-40a2-a9d4-5af1fa1a8551)
My config:
```json
{
    "input": "/mnt/C07F201295383FC7/Data/berxekl/box_full_png_PSGSDF/", 
    "output": "/mnt/C07F201295383FC7/Data/berxekl/box_full_png_PSGSDF/output3/",
    "datatype": "synth",
    "first": 0,
    "last": 200,
    "voxel size": 0.001,
    "truncation factor": 5,
    "zmin": 0.0,
    "zmax": 3.5,
    "sharpness threshold": 0.03,
    "model type": "LED",
    "loss function": "cauchy",
    "reg albedo": 0.0,
    "reg norm": 0.1,
    "reg laplacian": 5.0,
    "max iter": 100,
    "damping": 3.0,
    "converge threshold": 5e-3,
    "lambda": 0.2,
    "upsample":true,
    "--light": true,
    "--albedo": true,
    "--distance": true,
    "--pose": false
}
```

**Comment by kuwan2e** [comment]
some of my rgb data:
![000](https://github.com/Sangluisme/PSgradientSDF/assets/42766628/a24edf5f-ce49-460d-9111-a37f82d3f76f)
![066](https://github.com/Sangluisme/PSgradientSDF/assets/42766628/7ca77c18-0364-4cd2-8928-7a97512dc736)

**Comment by Sangluisme** [comment]
I saw you set "--pose false", which means you need to specify the poses of the sequence. Do you have the poses of the camera already? If not, the set "--pose true". You can try with "--upsample false" at very beginning. And if you use the data type "synth", that means your data format should be as described in README.md.

**Comment by Sangluisme** [comment]
And according to this:
      https://github.com/Sangluisme/PSgradientSDF/blob/ee5bb0289e33f7b82dec8504fb9650dc7ac2ff06/cpp/include/img_loader/SynthLoader.h#L24

The depth factor is 1000, which means the depth value divide by 1000, is the true distance. Please make sure your data format satisfies this.

**Comment by kuwan2e** [comment]
Thanks for your reply.
I found the reason. This is because the initialized griddim is (128, 128, 128). since I set voxel size=0.001, the volume is too small. After change it to (640, 640, 640), it worked.
BTW, I think parameter voxel_size is in **m** , not **cm**. Because my box is around 32cm length and 25cm width. If the unit is **cm** , the volume is around 0.64³ cm³, which cannot cover my box. But if it is **m**, I think this volume 64³ cm³ can cover the box.

**Comment by Sangluisme** [comment]
Yes, the unit for voxel size is **meter.** Sorry if we write it is **cm**. It should be correct in the paper. I'll check if the readme.md is also correct.

**Comment by Sangluisme** [comment]
I corrected the readme.md and add two trouble shooting for this problem. Sorry for the mistakes.

**Comment by kuwan2e** [comment]
Thanks!
