### ISSUE TITLE
How to change the marching cubes threshold

### ISSUE THREAD

**Issue by kuwan2e** [Sangluisme/PSgradientSDF#4]
![image](https://github.com/Sangluisme/PSgradientSDF/assets/42766628/97cfc349-c7c8-4ada-80fd-891dce395f04)
Hi . I captured a series of RGB-D images of a human. The result shows that there are many black holes, which I think maybe related to the threshold of marching cubes algorithm. Or some parameters for TSDF Integrate. So my question is how to change this threshold so that I can fill these holes. Thanks

**Comment by Sangluisme** [comment]
Hi, so here are several possibilities that you have holes. 
- First, the RGBD images may not be captured in these areas. So please try to move slowly and move around the same location several times to ensure that data are available in these areas. 
- Second, note that the default "--z_min", "--z_max" is "0.5" or "0.0" and "3.5" (in meters) which is the sweet range of intel realsense camera, not sure if you are outside this range. 
- for marching cube, what you can change is the iso-surface level, which means if you want the surface to be on zero level set or some other value. In general, I do not recommend to change this setting. But if you still need, change here the isovalue.
https://github.com/Sangluisme/PSgradientSDF/blob/d6921528ed68e830d06b99a1e39ae43ce5e0506c/cpp/third/mesh/MarchingCubes.h#L17
- If you want to change TSDF, especially the truncation, change in config such as
https://github.com/Sangluisme/PSgradientSDF/blob/d6921528ed68e830d06b99a1e39ae43ce5e0506c/config/config_basket_LED.json#L8
for weight, change in 
https://github.com/Sangluisme/PSgradientSDF/blob/d6921528ed68e830d06b99a1e39ae43ce5e0506c/cpp/include/sdf_tracker/Sdf.h#L48
this function.
